
# auto-generated by configure
PREFIX = /usr/local
VERSION = 2.5.2
CC = gcc
CFLAGS = -O3 -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -DNDEBUG -DUSE_SSE=1 -msse -Wno-unknown-pragmas -I/usr/include/libpng12       -DUSE_LCMS=1
LDFLAGS =  -lpng12   -lz   -llcms2   -lm
COCOA_READER = 0

